import { Outfit } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";



// Specify the weights you need for Roboto
const inter = Outfit({ subsets: ["latin"] })

export const metadata = {
  title: "NexGen Learn",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <GoogleOneTap />
        <body
          className={inter.className}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
