import { Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";



// Specify the weights you need for Roboto
const inter = Roboto({ 
  subsets: ["latin"], 
  weight: ["400", "900"]  // Specify the weights you need, e.g., 400 (normal) and 700 (bold)
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <GoogleOneTap />
        <body
          className={inter.className}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
