export default [
    {
        id:1,
        name:'Coding',
        icon:'/developer.svg',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/medical-team.svg',
        prompt:''
    },
    {
        id:3,
        name:'Creative',
        icon:'/design-thinking.svg',
        prompt:''
    },
    {
        id:4,
        name:'Cooking',
        icon:'/cooking.svg',
        prompt:''
    }
]